--
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER HLUO_ADMIN
IDENTIFIED BY "HLUO_ADMIN.PRUEBA_P1"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

CREATE USER HLUO_ADMIN
IDENTIFIED BY "HLUO_ADMIN"

ALTER USER HLUO_REPORT QUOTA UNLIMITED ON USERS;
ALTER USER HLUO_REPORT DEFAULT ROLE "RESOURCE";

-- 3
CREATE USER HLUO_REPORT QUOTA UNLIMITED ON USERS;

-- 4. OTORGAR PERMISOS BÁSICOS
GRANT CREATE SESSION TO HLUO_REPORT;
GRANT "RESOURCE" TO HLUO_REPORT;
ALTER USER HLUO_REPORT DEFAULT ROLE "RESOURCE";


GRANT CREATE PROCEDURE TO HLUO_REPORT;
GRANT CREATE MATERIALIZED VIEW TO HLUO_REPORT


----
-- DAR PERMISOS SOLO A TABLAS ESECÍFICAS

GRANT SELECT ON HLUO_ADMIN.AGENCIA TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.CATEGORIA TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.DETALLE_DIARIO_HUESPEDES TO HLUO_REPORT;

GRANT SELECT ON HLUO_ADMIN.HUESPED_TOUR TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.TOTAL_CONSUMOS TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.CONSUMO TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.INCENTIVOS TO HLUO_REPORT;

GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.HUESPED_TOUR TO HLUO_REPORT;
GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.TOTAL_CONSUMOS TO HLUO_REPORT;
GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.CONSUMO TO HLUO_REPORT;
GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.INCENTIVOS TO HLUO_REPORT;
