-- script actualizado

CREATE USER C##BDY1102 IDENTIFIED BY "BDY1101practica_1"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
CREATE ROLE C##RESOURCE CONTAINER=ALL;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO C##RESOURCE CONTAINER=ALL;
GRANT C##RESOURCE TO C##BDY1102 CONTAINER=ALL;
ALTER USER C##BDY1102 DEFAULT ROLE C##RESOURCE;
ALTER USER C##BDY1102 QUOTA UNLIMITED ON USERS;
